import pandas as pd
from datetime import datetime
import pathlib

# Configuration
PERFORMANCE_LOG = pathlib.Path("logs/performance.csv")
REPORT_OUTPUT = pathlib.Path("logs/substack_report.md")
# UPDATE THIS with your GitHub Pages or hosted URL
INTERACTIVE_URL = "https://your-username.github.io/portfolio-experiment" 

def generate_report():
    if not PERFORMANCE_LOG.exists():
        print(f"❌ Error: {PERFORMANCE_LOG} not found. Run log_performance.py first.")
        return

    # Load data
    df = pd.read_csv(PERFORMANCE_LOG)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date')

    if len(df) < 2:
        print("❌ Error: Need at least 2 days of data for a comparison report.")
        return

    # Get latest and previous data
    latest = df.iloc[-1]
    last_week = df.iloc[-6] if len(df) >= 6 else df.iloc[0] # Compare to start of week or first record
    
    start_capital = 1000.0
    models = [c for c in df.columns if c != 'Date']

    # Generate Markdown
    report = []
    report.append(f"# 📊 AI Trading Challenge: Weekly Performance Report (TEST RUN)")
    report.append(f"**Period**: {last_week['Date'].strftime('%b %d')} - {latest['Date'].strftime('%b %d, %Y')}\n")

    # 1. Summary Table
    report.append("## 📈 Portfolio Overview")
    report.append("| AI Model | Current Equity | Total Return (%) | Weekly Delta |")
    report.append("| :--- | :--- | :--- | :--- |")

    for model in models:
        current = float(latest[model])
        prev = float(last_week[model])
        total_return = ((current - start_capital) / start_capital) * 100
        weekly_delta = ((current - prev) / prev) * 100
        
        delta_str = f"{weekly_delta:+.2f}%"
        report.append(f"| {model} | ${current:,.2f} | {total_return:+.2f}% | {delta_str} |")

    report.append("\n## 🏆 Leaderboard")
    sorted_models = sorted(models, key=lambda m: float(latest[m]), reverse=True)
    for i, model in enumerate(sorted_models):
        medal = "🥇" if i == 0 else ("🥈" if i == 1 else ("🥉" if i == 2 else "📉"))
        report.append(f"{medal} **{model}**: ${latest[model]:,.2f}")

    report.append(f"\n---")
    report.append(f"🔗 **[View Interactive Dashboard]({INTERACTIVE_URL})**")
    report.append("*Generated by Antigravity Performance Engine*")

    # Save to file
    with open(REPORT_OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(report))

    print(f"\n✅ Substack-ready report generated at: {REPORT_OUTPUT}")
    print("\n--- REPORT PREVIEW ---")
    print("\n".join(report))

if __name__ == "__main__":
    generate_report()
